### PR TITLE
Changed custom date formatting import statement #78

### PR DESCRIPTION
**Pull request by jrdevforlife**
Thank you very much for that opportunity.
For issue #78

### CODE REVIEW

**Comment by jrdevforlife** [comment]
@arshadkazmi42 Sure will do. Thanks again for the hint.

**Comment by arshadkazmi42** [comment]
@jrdevforlife you have tagged the wrong issue number. Correct number is `#78`

**Comment by jrdevforlife** [comment]
Oh my fault, it has linked me to that. Stupid me :3rd_place_medal:

**Comment by arshadkazmi42** [comment]
@jrdevforlife thank you for working on this

**Pull request merged**
