### PR TITLE
adds Mike Tobias to contributors

### PR DESCRIPTION
**Pull request by mct-dev**
First PR! :1st_place_medal: #20

### CODE REVIEW

**Comment by mct-dev** [comment]
ok @arshadkazmi42 I've added the issue number

**Comment by arshadkazmi42** [comment]
@mct-dev you have to add the issue number in description, not in title, so it will create a link between both

**Comment by mct-dev** [comment]
Hmm...having trouble figuring out where the "description" part of the PR is. lol.  Do I need to add it in a commit?  Or just in a comment here, like #20?

**Comment by arshadkazmi42** [comment]
Where you have written first pr that is description part of PR

**Comment by mct-dev** [comment]
Ohhh, gotcha.  It's just the first comment on the PR.  OK it's updated @arshadkazmi42

**Comment by arshadkazmi42** [comment]
Merged

**Pull request merged**
