### PR TITLE
Added Contributors List in README.md file

### PR DESCRIPTION
**Pull request by rogers9798**

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
@rogers9798 Thank you for working on this.
Looks good.
Just few changes,
You are trying to fix two issues in the same commit, I will suggest you to create two seperate pull request, one for each issue.

You can tackle adding contributors issue in this PR and create another PR for test case cleanup.
Also tag the issue you are working on in PR description

Also need to confirm, have to checked all the tests? Are they passing?


Also its not good practice to work on master branch. you should always work on the feature branch, this is fine for this one, you can take care of this from next branch onwards

**Comment by rogers9798** [comment]
@arshadkazmi42 
Yes, all checks have been passed on both commits.
Thanks for suggesting to work on a feature branch.

**Comment by arshadkazmi42** [comment]
@rogers9798 You have just made different commits in same Pull Request, You should create two different pull request.

Remove the changes you have done in the test file in this pull request, just add README changes in this Pull Request

then create a new branch in your local from master and make test cases cleanup changes there, then create a new Pull request using that branch

**Comment by rogers9798** [comment]
ok.

**Comment by arshadkazmi42** [comment]
@rogers9798 Now you have deleted index.js file. Thats not what I meant. I mean you remove the changes you did.

Let's do it fresh, I understand this is your first PR.
I did the same mistakes in my first PR too.

remove everything you have in your local

1. Clone fresh repo
2. Go to the project directory
3. Run the following commands
- `git checkout -b update-readme`
4. Make the readme related changes
5. `git add --all`
6. `git commit -m "added contributors avatar to readme"`
7. `git push origin update-readme`
8. Create pull request
9. `git checkout master`

Follow the same above steps for test/index.js changes.
Just use different branch name in `git checkout -b test-cleanup`

**Pull request closed without merging**
