### PR TITLE
Update contributor.md

### PR DESCRIPTION
**Pull request by parammittal16**
Issue #20

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
@parammittal16 looks good. can you tag the issue number to the PR description. I will merge it as soon as you do that change

**Comment by parammittal16** [comment]
Done sir

**Comment by parammittal16** [comment]
Done sir

**Comment by arshadkazmi42** [comment]
@parammittal16 Cool. Congrats on your first PR

**Comment by parammittal16** [comment]
Thank you sir

**Pull request merged**
